### ISSUE TITLE
Put fsproj from root into src

### ISSUE THREAD

**Issue by forki** [fable-elmish/templates#17]
@enricosada said this. Otherwise issues with ionide and FSAC

**Comment by MangelMaxime** [comment]
@enricosada What's the issue ?

I am just asking because I have no problem with the current architecture when using Ionide and FSAC.

**Comment by forki** [comment]
If I understand correctly it trying to look into way to many files. like going down in `.git` and `node-modules` and `packages`. Therefor it's slow.

**Comment by MangelMaxime** [comment]
Ah yes, I agree that I find it slow to start. :)

**Comment by alfonsogarciacaro** [comment]
The main problem with moving the .fsproj file is then you cannot run the `dotnet fable` command from the root... Unless you create an extra `Fable.proj` file just to download the dotnet-fable cli tool, but then we lose? the new Paket feature for managing dotnet cli tools.

> If I understand correctly it trying to look into way to many files. like going down in .git and node-modules and packages. Therefor it's slow.

These folders (plus `bin` and `obj`) should probably be omitted from the search by default.

**Comment by forki** [comment]
btw: https://github.com/fable-elmish/templates/pull/19

**Comment by forki** [comment]
@alfonsogarciacaro  https://github.com/fable-compiler/fable-react_native-demo/pull/24 shows the dotnet-fable works with subfolders

**Comment by alfonsogarciacaro** [comment]
Yeah, but then you need FAKE for everything... I know, I know, I'm not against FAKE but I think it's important users can easily run Fable directly with a single CLI command :wink: We can use FAKE here but we'd have the same problem in the basic template.

@enricosada Can you comment on this situation (not being able to run `dotnet fable` from root if we move the project file)? At the moment we have these alternatives:

- Just tell the user to move to `src` dir
- Start the command with an npm script
- Use FAKE by default
- Add an empty `Fable.proj` and `paket.references`to root just to download the fable cli tool
- Don't move the project and add omit search in `.git` (actually all folders starting by `.`), `packages` and `node_modules` in FSAC. BTW, why FSAC is not checking first the files in the directory instead of looking in the subfolders?

**Comment by forki** [comment]
@alfonsogarciacaro no you don't need fake. It's just like the dotnet cli is working everywhere. You need to run things from project folder. that's all (and yes I don't really like it, but that's MS way to do things)

**Comment by enricosada** [comment]
> Otherwise issues with ionide and FSAC

Issue is not with ionide/fsac. is of `dotnet` (specificially doing stuff with `dotnet msbuild` based command like `build` or `restore`), because there are some globbing in place for stuff (like `None`), so you need to at least exclude `node_modules` afaik.
Maybe i can check how disable these, like the include of `**/*` for `None`, this should avoid the issue.
a way to do is is run any slow command (like `dotnet restore`) with `-v diag`, or better `dotnet msbuild /t:Restore /v:diag` and see what is consuming time (there is a perf summary at end, plus lot of data)

**Comment by MangelMaxime** [comment]
Has been fixed.

- React: 0.1.4
- React demo: 0.2.6
