### ISSUE TITLE
dotnet fable not working

### ISSUE THREAD

**Issue by Kurren123** [fable-elmish/templates#23]
I run the following:
```
dotnet new -i Fable.Template.Elmish.React::*
dotnet new fable-elmish-react
yarn install
dotnet restore
dotnet fable yarn-run start
```
With the last command I get `No executable found matching command "dotnet-fable"`. However the same commands work with the standard fable template `dotnet new fable`.

**Comment by Kurren123** [comment]
I'm not sure what `clitool` does in the `paket.dependencies` file as I cant find any docs. I'm guessing it's meant to add `<DotNetCliToolReference Include="dotnet-fable" Version="1.1.6" />` to the project file but it's failing to do that.

**Comment by alfonsogarciacaro** [comment]
@Kurren123 Please note the .fsproj has been moved to `src` folder (this had to be done because of some problems with latest dotnet SDK preview), so it's necessary to move to that folder before the last two steps ([as indicated in the updated README](https://github.com/fable-elmish/templates/blob/master/src/react/Content/README.md#building-and-running-the-app)):

```
cd src
dotnet restore
dotnet fable yarn-run start
```

**Comment by alfonsogarciacaro** [comment]
Related: https://github.com/fable-elmish/templates/issues/17

**Comment by Kurren123** [comment]
@alfonsogarciacaro  sorry, silly mistake. Thanks for the help!

**Comment by alfonsogarciacaro** [comment]
No worries, I know changing the instructions so often is annoying for users! Luckily we're already entering a stable phase and things shouldn't change so quickly now :)
