### ISSUE TITLE
Error yarn-build: Module build failed: Error: "es2015" in babel.presets is not resolved to an absolute path

### ISSUE THREAD

**Issue by richardjharding** [fable-elmish/templates#26]
Have installed the latest template
,net cli tools 2.0.0
.net core 2.0.0
npm: 5.3.0
node 8.4.0

After following the instructions here I ran dotnet fable yarn-run start and got the following error

`
ERROR in ./src/awesome.fsproj
Module build failed: Error: "es2015" in babel.presets is not resolved to an absolute path. Please use `require("fable-utils")
.resolveBabelOptions(babelOptions)` (also when passing the options to other plugins like babel-loader). Check https://goo.gl/
dsBqWA for an example.
    at C:\Users\richa\awesome\node_modules\fable-utils\index.js:41:27
    at Array.forEach (<anonymous>)
    at validateArray (C:\Users\richa\awesome\node_modules\fable-utils\index.js:38:33)
    at Object.exports.validateFableOptions (C:\Users\richa\awesome\node_modules\fable-utils\index.js:52:9)
    at Object.Loader (C:\Users\richa\awesome\node_modules\fable-loader\index.js:43:20)
`

Am I missing some dependency or is this an error in the template?

running npm install --save-dev fable-utils
and re-running the build works so looks like a missing dep in package.json?

**Comment by MangelMaxime** [comment]
Hello @richardjharding I believe you used the template with the npm version but used `yarn` to manage your deps.

So yarn generated a new lock file instead of the one include when installing the template wtih "yarn support". `dotnet new fable-elmish-react -n awesome -yarn`.

So you installed the latest version of `fable-loader` which emit an error when we don't have absolute path to resolve the babelOptions. This is needed to support `storage:none` feature of paket with Fable 1.2

So @richardjharding you can keep using the template as you fixed it. Also, you are under .net core 2.0 and the template is for .net core 1.0 so you could also encounter problem here. I need to update the templates.

@alfonsogarciacaro I believe we didn't respected the semver convention when introducing the warning about `fable-utils` being missing. 

Should we fix the `fable-loader` versions to follow semver convention too ?

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime That's tricky because we wanted to add the warning so people using Fable 1.2 would remember to resolve Babel options... though apparently the error message was not informative enough ;)

I don't think following semver in this case would solve anything, because npm and Nuget versions are not related, so people using Fable 1.2 may stil have problems if they don't resolve the Babel options, they will just not get the warning if they use the _old_ fable-utils.

**Comment by MangelMaxime** [comment]
Hum, yes true.

I will update the templates and this should be enough.

**Comment by MangelMaxime** [comment]
Hum, I see why @richardjharding got this error too.

I will update the README too.

**Comment by MangelMaxime** [comment]
Ok, I'm closing as I added more instruction into the readme and update both templates.
